apiVersion: v1
kind: PersistentVolume
metadata:
  name: hard-drive-config-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/q-config
    server: 192.168.1.6
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
